import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
await page.goto('http://127.0.0.1:3000/login',{waitUntil:'networkidle'});
const payload=await page.evaluate(async()=>{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'owner',password:'Owner@12345'})});return r.json();});
await page.evaluate(p=>{sessionStorage.setItem('auth-storage',JSON.stringify({state:{user:p.user,isAuthenticated:true},version:0})); localStorage.setItem('branch-storage',JSON.stringify({state:{branches:p.branches,activeBranch:p.active_branch},version:0}));}, payload);
console.log('storage', await page.evaluate(()=>sessionStorage.getItem('auth-storage')));
await page.goto('http://127.0.0.1:3000/',{waitUntil:'domcontentloaded'});
await page.waitForTimeout(5000);
console.log('url', page.url());
console.log('text len', (await page.locator('body').innerText()).length, (await page.locator('body').innerText()).slice(0,500));
console.log('storage2', await page.evaluate(()=>sessionStorage.getItem('auth-storage')));
await browser.close();
