import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport:{width:1440,height:900} });
page.on('console', msg => console.log('console', msg.type(), msg.text()));
page.on('pageerror', err => console.log('pageerror', err.message));
await page.goto('http://127.0.0.1:3000/login', {waitUntil:'domcontentloaded'});
await page.waitForTimeout(3000);
console.log('url', page.url());
console.log('title', await page.title());
console.log('body text', (await page.locator('body').innerText().catch(e=>'ERR '+e.message)).slice(0,500));
console.log('html len', (await page.content()).length);
await browser.close();
