import { chromium } from 'playwright';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
page.on('response', async r=>{ if(r.url().includes('/api/auth/login')) console.log('login response', r.status(), await r.text().catch(()=>'')); });
await page.goto('http://127.0.0.1:3000/login',{waitUntil:'networkidle'});
await page.locator('input[autocomplete="username"]').click();
await page.keyboard.type('owner');
await page.locator('input[autocomplete="current-password"]').click();
await page.keyboard.type('Owner@12345');
await page.keyboard.press('Enter');
await page.waitForTimeout(5000);
console.log('url', page.url());
console.log('text', (await page.locator('body').innerText()).slice(0,300));
await browser.close();
